version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - ./.rabbitmqdata:/var/lib/rabbitmq

  consumerthree:
    build:
      context: ./consumer_three
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/stockmanager
    depends_on:
      - db
      - rabbitmq
  
  consumertwo:
    build:
      context: ./consumer_two
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - .:/itemcreation
    depends_on:
      - db
      - rabbitmq

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/producer
    depends_on:
      - db
      - rabbitmq  

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

    