version: "3.8"

volumes:
  mongodata:

networks:
  resolute:
    name: resolute
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672" # For RabbitMQ management interface
      - "5672:5672" # For RabbitMQ message broker
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - resolute

  mongodb:
    image: mongo:latest
    hostname: mongo_test
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: database
    ports:
      - "27017:27017"
    restart: always
    logging:
      driver: none
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - resolute

  producer:
    build: Producer/
    ports:
      - "5000:5000" # For Flask server
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - resolute
    links:
      - mongodb
      - rabbitmq

  consumer_health_check:
    build: Consumer_one/
    depends_on:
      producer:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - resolute
    links:
      - mongodb
      - rabbitmq

  consumer_insert_record:
    build: Consumer_two/
    depends_on:
      producer:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - resolute
    links:
      - mongodb
      - rabbitmq

  consumer_delete_record:
    build: Consumer_three/
    depends_on:
      producer:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - resolute
    links:
      - mongodb
      - rabbitmq

  consumer_read_database:
    build: Consumer_four/
    depends_on:
      producer:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - resolute
    links:
      - mongodb
      - rabbitmq
