FROM python:3.9
ENV PYTHONBUFFERED 1
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./stock_managment.py /code/

CMD ["uvicorn", "stock_managment:app", "--host", "0.0.0.0", "--port", "8000"]