version: '3'

services:
 mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 2002
      MYSQL_DATABASE: student_project
    networks:
      - app_network

    volumes:
      - ./sql_data:/data

networks:
 app_network:
    external: true
